//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DLCup.Common.Model
{
    public partial class Cup
    {
        #region Primitive Properties
    
        public virtual int CupId
        {
            get;
            set;
        }
    
        public virtual System.DateTime CupDate
        {
            get;
            set;
        }
    
        public virtual string CupName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Team GuestTeam
        {
            get;
            set;
        }
    
        public virtual Team HomeTeam
        {
            get;
            set;
        }
    
        public virtual ICollection<Match> Matches
        {
            get
            {
                if (_matches == null)
                {
                    var newCollection = new FixupCollection<Match>();
                    newCollection.CollectionChanged += FixupMatches;
                    _matches = newCollection;
                }
                return _matches;
            }
            set
            {
                if (!ReferenceEquals(_matches, value))
                {
                    var previousValue = _matches as FixupCollection<Match>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMatches;
                    }
                    _matches = value;
                    var newValue = value as FixupCollection<Match>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMatches;
                    }
                }
            }
        }
        private ICollection<Match> _matches;

        #endregion
        #region Association Fixup
    
        private void FixupMatches(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Match item in e.NewItems)
                {
                    item.Cup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Match item in e.OldItems)
                {
                    if (ReferenceEquals(item.Cup, this))
                    {
                        item.Cup = null;
                    }
                }
            }
        }

        #endregion
    }
}
