//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace DLCup.Common.Model
{
    public partial class DLCupEntities : ObjectContext
    {
        public const string ConnectionString = "name=DLCupEntities";
        public const string ContainerName = "DLCupEntities";
    
        #region Constructors
    
        public DLCupEntities()
            : base(ConnectionString, ContainerName)
        {
        }
    
        public DLCupEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
        }
    
        public DLCupEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Cup> Cups
        {
            get { return _cups  ?? (_cups = CreateObjectSet<Cup>("Cups")); }
        }
        private ObjectSet<Cup> _cups;
    
        public ObjectSet<Game> Games
        {
            get { return _games  ?? (_games = CreateObjectSet<Game>("Games")); }
        }
        private ObjectSet<Game> _games;
    
        public ObjectSet<Match> Matches
        {
            get { return _matches  ?? (_matches = CreateObjectSet<Match>("Matches")); }
        }
        private ObjectSet<Match> _matches;
    
        public ObjectSet<Player> Players
        {
            get { return _players  ?? (_players = CreateObjectSet<Player>("Players")); }
        }
        private ObjectSet<Player> _players;
    
        public ObjectSet<Team> Teams
        {
            get { return _teams  ?? (_teams = CreateObjectSet<Team>("Teams")); }
        }
        private ObjectSet<Team> _teams;

        #endregion
    }
}
